insert into product (name, price, weight_in_grams) values ('Bar Mix - Lime', 444.17, 361);
insert into product (name, price, weight_in_grams) values ('Muffin Mix - Morning Glory', 382.94, 1607);
insert into product (name, price, weight_in_grams) values ('Beans - Fava Fresh', 480.56, 211);
insert into product (name, price, weight_in_grams) values ('Fenngreek Seed', 469.48, 1273);
insert into product (name, price, weight_in_grams) values ('Wine - White, Pinot Grigio', 217.48, 1070);
insert into product (name, price, weight_in_grams) values ('Tart - Raisin And Pecan', 881.47, 1528);
insert into product (name, price, weight_in_grams) values ('Soup - French Can Pea', 703.26, 1);
insert into product (name, price, weight_in_grams) values ('Hersey Shakes', 757.48, 853);
insert into product (name, price, weight_in_grams) values ('Lettuce - Red Leaf', 356.88, 22);
insert into product (name, price, weight_in_grams) values ('Longan', 137.98, 788);
insert into product (name, price, weight_in_grams) values ('Pie Filling - Apple', 56.1, 1696);
insert into product (name, price, weight_in_grams) values ('Tart Shells - Savory, 3', 379.69, 1508);
insert into product (name, price, weight_in_grams) values ('Skewers - Bamboo', 180.93, 1737);
insert into product (name, price, weight_in_grams) values ('Chef Hat 20cm', 44.36, 100);
insert into product (name, price, weight_in_grams) values ('Mushroom - Oyster, Fresh', 27.93, 1409);
insert into product (name, price, weight_in_grams) values ('Red Pepper Paste', 131.78, 1316);
insert into product (name, price, weight_in_grams) values ('Rice - Basmati', 518.86, 1097);
insert into product (name, price, weight_in_grams) values ('Brandy Cherry - Mcguinness', 744.91, 1481);
insert into product (name, price, weight_in_grams) values ('Wine - Pinot Noir Mondavi Coastal', 692.84, 799);
insert into product (name, price, weight_in_grams) values ('Wine - Penfolds Koonuga Hill', 410.51, 1261);

insert into delivery (delivery_date, from_warehouse, destination) values ('2023-08-16', 'Gerhold LLC', '45 Buena Vista Road');
insert into delivery (delivery_date, from_warehouse, destination) values ('2023-12-06', 'Hoppe Group', '87 Prairie Rose Pass');
insert into delivery (delivery_date, from_warehouse, destination) values ('2024-02-01', 'Simonis Group', '465 Talisman Way');
insert into delivery (delivery_date, from_warehouse, destination) values ('2023-07-07', 'Hartmann, Mertz and Tromp', '16 Northridge Center');
insert into delivery (delivery_date, from_warehouse, destination) values ('2023-05-04', 'Goyette, Purdy and Sanford', '630 Melvin Place');
insert into delivery (delivery_date, from_warehouse, destination) values ('2023-11-01', 'Walsh and Sons', '62 Warrior Parkway');
insert into delivery (delivery_date, from_warehouse, destination) values ('2023-05-31', 'Schowalter and Sons', '99 Duke Junction');
insert into delivery (delivery_date, from_warehouse, destination) values ('2023-12-10', 'Zemlak-Crona', '29 Jenna Circle');
insert into delivery (delivery_date, from_warehouse, destination) values ('2024-01-09', 'Rodriguez Inc', '62 Kennedy Hill');
insert into delivery (delivery_date, from_warehouse, destination) values ('2024-03-04', 'Kulas, Kozey and Streich', '4748 Summit Point');

insert into product_order (product_id, delivery_id, quantity) values (6, 5, 6);
insert into product_order (product_id, delivery_id, quantity) values (2, 1, 9);
insert into product_order (product_id, delivery_id, quantity) values (5, 6, 16);
insert into product_order (product_id, delivery_id, quantity) values (7, 4, 13);
insert into product_order (product_id, delivery_id, quantity) values (9, 6, 19);
insert into product_order (product_id, delivery_id, quantity) values (2, 10, 14);
insert into product_order (product_id, delivery_id, quantity) values (5, 4, 16);
insert into product_order (product_id, delivery_id, quantity) values (5, 9, 16);
insert into product_order (product_id, delivery_id, quantity) values (8, 2, 5);
insert into product_order (product_id, delivery_id, quantity) values (4, 4, 14);
